# Generated by Django 3.2.3 on 2021-05-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priceplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(blank=True, max_length=200, null=True)),
                ('package_price', models.CharField(blank=True, max_length=5, null=True)),
                ('hourly_rates', models.CharField(blank=True, default='20', max_length=200, null=True)),
                ('package_description', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Priceplans',
            },
        ),
    ]
