export const PROGRAMMER_LIST_REQUEST = 'PROGRAMMER_LIST_REQUEST'
export const PROGRAMMER_LIST_SUCCESS = 'PROGRAMMER_LIST_SUCCESS'
export const PROGRAMMER_LIST_FAIL = 'PROGRAMMER_LIST_FAIL'

export const PROGRAMMER_DETAILS_REQUEST = 'PROGRAMMER_DETAILS_REQUEST'
export const PROGRAMMER_DETAILS_SUCCESS = 'PROGRAMMER_DETAILS_SUCCESS'
export const PROGRAMMER_DETAILS_FAIL = 'PROGRAMMER_DETAILS_FAIL'