# Generated by Django 3.2.3 on 2021-05-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0002_auto_20210514_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, max_length=200, null=True)),
                ('programmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmers.programmer')),
            ],
            options={
                'verbose_name_plural': 'Qualifications',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('web_link', models.CharField(blank=True, max_length=200, null=True)),
                ('git_link', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('programmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmers.programmer')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Experty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.CharField(blank=True, max_length=200, null=True)),
                ('programmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmers.programmer')),
            ],
            options={
                'verbose_name_plural': 'Expertiese',
            },
        ),
    ]
