# Generated by Django 3.2.3 on 2021-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0003_experty_project_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
