# Generated by Django 3.2.3 on 2021-05-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0004_auto_20210514_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='hourly_rates',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='qualificaiton',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='user',
        ),
        migrations.AddField(
            model_name='programmer',
            name='project_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='programmer',
            name='project_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='programmer',
            name='project_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='image',
            field=models.ImageField(blank=True, default='/default.jpg', null=True, upload_to=''),
        ),
    ]
