# Generated by Django 3.2.3 on 2021-05-15 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0005_auto_20210515_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='project_image_1',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='project_image_2',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='project_image_3',
        ),
        migrations.AddField(
            model_name='programmer',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='hourly_rates',
            field=models.CharField(blank=True, default='add qualificaiton', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programmer',
            name='qualificaiton',
            field=models.CharField(blank=True, default='add qualificaiton', max_length=200, null=True),
        ),
    ]
