# Generated by Django 3.2.3 on 2021-05-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0006_auto_20210515_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='hourly_rates',
            field=models.CharField(blank=True, default='20', max_length=200, null=True),
        ),
    ]
